---
- hosts: 192.168.20.60
  tasks:
    - name: Comprimir el directorio '/home/otrousuario/ansibleLabs' con tar
      archive:
        path: '/home/otrousuario/ansibleLabs'
        dest: '/home/otrousuario/ansibleLabs.tar'
        format: tar
