---
- hosts: 192.168.20.60
  tasks:
    - name: Comprimir el archivo '/home/otrousuario/ansibleLabs/00/ansible.txt'
      archive:
        path: '/home/otrousuario/ansibleLabs/00/ansible.txt'
        dest: '/home/otrousuario/ansible.txt.gz'

