---
- hosts: servidores
  tasks:
    - name: Ejecuta el comando 'df' en los servidores
      register: salidadf
      command: "df -h"

    - debug:
        var: salidadf.stdout_lines

    - local_action: 
        module: file  # Eliminamos el fichero si existe.
        path: '~/ansibleLabs/Ejercicios/03_02_uso_de_disco.log'
        state: absent

    - local_action:
        module: lineinfile # Creamos y añadimos líneas.
        create: yes
        line: "{{ ansible_hostname }}\n------------------\n{{ salidadf.stdout }}\n\n"
        insertafter: EOF
        dest: '~/ansibleLabs/Ejercicios/03_02_uso_de_disco.log'
