- hosts: 192.168.20.60  # No olvidemos eque en 'ansible.cfg' se indica 'remote_user' y 'become'.
   
  vars:      # Esta sección define las variables.
    planetas: [Mercurio, Venus, Tierra, Marte, Júpiter, Saturno, Urano, Neptuno]

  tasks:
    - name: Ejemplo de uso de lista
      debug:
        msg: "{{ item }}"    # Referencia al elemento que se itera.
      with_items:          # Enumera la lista...
        - "{{ planetas }}" # Planetas.






