# Indicamos las máquinas en las que se aplicará la configuración.
- hosts: servidores  # Ubu_srv_01 y Ubu_srv_02
  become: true       # Todas las tareas se ejecutarán con permisos de SUDO.
 
  tasks:
    - name: Borra el archivo '/foo.txt'
      ansible.builtin.file:     # Usamos el módulo file.
        path:  /foo.txt         # El archivo.
        state: absent           # El estado deseado es que esté ausente (borrado)
    







  

