---
- hosts: router_03
  gather_facts: no
  connection: local

  tasks:
    - name: Cargar variables
      include_vars: 07_data_router_03.yaml
      
    - name: Generar archivo de configuración para el router_03
      template:
        src: "07_template.j2"
        dest: "07_{{ inventory_hostname }}.cfg"


