---
- hosts: router_01
  gather_facts: no
  connection: local

  tasks:
    - name: Cargar variables
      include_vars: 11_data.yaml
      
    - name: Generar archivo de configuración para el router_01
      template:
        src: "11_template.j2"
        dest: "11_{{ inventory_hostname }}.cfg"

